accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # login
    path('login/', views.login_view, name='login'),
    #logout
    path('logout', views.logout_view, name='logout'),
    #registration
    path('signup', views.signup_view, name='signup'),
    
    path('change/password',views.ChangePasswordView.as_view(),name="change-password"),
    path('password_reset', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import BlogPostFeed

app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', BlogPostFeed()),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap, WebsiteSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'website': StaticViewSitemap,
    'blog': BlogSitemap,
    'website': WebsiteSitemap
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
            name='django.contrib.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/',include('captcha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
     
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


# Create your models here.

class UserCreationForm(UserCreationForm):
    email = models.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        
        
class AuthenticationForm(AuthenticationForm):
    email = models.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from django.core import validators
from django.contrib.auth.forms import (PasswordChangeForm,
                                       ReadOnlyPasswordHashField)
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import (PasswordChangeForm,
                                       ReadOnlyPasswordHashField)
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField
# from .models import User



class SignUpForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields=('username','email','password1','password2')

class LoginForm(AuthenticationForm):
    captcha = CaptchaField()
    remember_me = forms.BooleanField(required=False)

class ChangePasswordForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput({'placeholder': "Previous password", 'id': "old_password"}))
    new_password1 = forms.CharField(widget=forms.PasswordInput({'placeholder': "New password", 'id': "new_password1"}))
    new_password2 = forms.CharField(widget=forms.PasswordInput({'placeholder': "Repeat new password", 'id': "new_password2"}))

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise ValidationError("your previous password was incorrect, please try again")
        return old_password


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'is_active', 'is_superuser','is_staff')
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages, auth
from accounts.models import *
from django.contrib.auth.views import (PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from accounts.forms import *
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.

def login_view(request):
    #if request.user.is_authenticated:
     #   msg = f'You are already logged in as {request.user.username}'
    #else:
     #   msg = 'You are not  logged in'
    #return render(request, 'accounts/login.html', {'msg': msg})
    
    
    
    if not request.user.is_authenticated:
        if request.method == 'POST':
            userinput = request.POST['username']
            try:
                username = User.objects.get(email=userinput).username
            except User.DoesNotExist:
                username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            if user is not None:
                auth.login(request, user)
                messages.add_message(request,messages.SUCCESS,'Login was successful')
                print(request.path)
                return redirect(request.path)
            else:
                 messages.add_message(request,messages.ERROR,'The desired person was not found')
        form = LoginForm()         
        return render(request, "accounts/login.html", {'form':form})
    else:
          return redirect('/')
        





def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('/')
    else:
        return HttpResponseRedirect(reverse('accounts:login'))

def logout_view(request):
    #  if request.user.is_authenticated:
          logout(request)
          return redirect('/')

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method=="POST":
              form=SignUpForm(request.POST)
              if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Now you can sign in')
                return redirect('accounts:login')
             
              else:
                messages.add_message(request, messages.ERROR, 'something went wrong')
        # form=UserCreationForm()
        form=SignUpForm()
        context={'form':form}
        return render(request,'accounts/signup.html',context)
    else:
          return redirect('/')
   
   
class ChangePasswordView(PasswordChangeView):
     template_name = 'accounts/change_password.html'
     success_url = reverse_lazy('accounts:login')
     form_class = ChangePasswordForm 
    
class PasswordReset(PasswordResetView):
    template_name="accounts/password_reset_form.html"
    success_url=reverse_lazy("accounts:password_reset_done")

class PasswordResetDone(PasswordResetDoneView):
    template_name="accounts/password_reset_done.html"
    success_url=reverse_lazy("accounts:password_reset_confirm")

class PasswordResetConfirm(PasswordResetConfirmView):
    template_name="accounts/password_reset_confirm.html"
    success_url=reverse_lazy("accounts:password_reset_complete")

class PasswordResetComplete(PasswordResetCompleteView):
    template_name="accounts/password_reset_complete.html"
    

templates/accounts/change_password.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">

          <form method="post" action="#">
            {%csrf_token%}
            <h1 class="h3 mb-3 font-weight-normal">Password  Change</h1>
              
            {{form.as_p}} 
                 
            <button class="btn btn-primary btn-lg" type="submit">change password</button>
             <br>
             <br>  

          </form>
            
        </div>

        <div class="col-sm-4">
        </div>
        
      </div>
    </div>
{% endblock %}

templates/accounts/login.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">
          <form class="form-signin" method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <br>
            <br>
            <h6 class="h4 mb-3 font-weight-normal">Please sign in to see all the posts</h6>
            
            <input type="text" name="username" class="form-control" placeholder="Username OR Email" required autofocus>
            <br>
            <input type="password" name="password" class="form-control" placeholder="Password" required>
            <div class="checkbox mb-3">
              
            </div>
            <div>
            {{form.captcha}}
            </div>
            <br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
            <a href="{% url 'accounts:password_reset'%}" class="link-secondary text-decoration-none">Forgot Your Password?</a>
            
            <p class="mt-5 mb-3 text-muted">Dont Have an Account?<a href="{% url 'accounts:signup' %}">Singn Up</a></p>
          </form>
        </div>
        <div class="col-sm-4">
        </div>
      </div>
    </div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">
          <form method="post" action="{%url 'accounts:password_reset_done'%}">
            {%csrf_token%}
            <h1 class="h3 mb-3 font-weight-normal">Password Reset Complete</h1>
        
            <p>Your new password has been set. You can log in now on the <a href=" {% url 'accounts:login' %}">log in page</a>.</p>
                 
          </form>
        </div>

        <div class="col-sm-4">
        </div>

      </div>
    </div>
    {% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">

          {% if validlink %}
         
          <form method="post" action="#">
          {%csrf_token%}
          <br>
            <h1 class="h3 mb-3 font-weight-normal">Password Reset Confirmation</h1>
         
            {{form.as_p}}

            <button class="btn btn-primary btn-lg" type="submit">change password</button>
                    
          </form>
          {% else %}
<br>
            <p>The password reset link was invalid, possibly because it has already been used. Please request a new password reset.</p>

          {% endif %}
        </div>

        <div class="col-sm-4">
        </div>
        
      </div>
    </div>
    {% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">
          <br>
              <form method="post" action="{%url 'accounts:password_reset_done'%}">
                {%csrf_token%}
                <h4 class="text-center mb-4">Password reset done</h4>
               <h4 class="text-center mb-4">Email successfully sent to user</h4>
                
                  <p>We've emailed you instructions for setting your password. If they haven't arrived in a few minutes, check your spam folder.</p>
                  <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg">Return to Sign in</a>
               
              </form>
              <br>
            </div>
            <div class="col-sm-4">
            </div>
          </div>
        </div>
    {% endblock %}

templates/accounts/password_reset_email.html
<p>Hi</p>

        <p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>
        
        <p>Please click the following link to reset your password:</p>
        
        {{ protocol}}://{{ domain }}{% url 'django.contrib.auth.views.password_reset_confirm' uidb64=uid token=token %}
        
        <p>Thanks</p>
        <p>Payam Bagheri</p>

templates/accounts/password_reset_form.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">

          <form class="form-signin" method="post" action="{%url 'accounts:password_reset'%}">
                {%csrf_token%}
              
                <h1 class="h3 mb-3 font-weight-normal">Forgot your password?</h1>
                
                
                  <!-- {{form.as_p}} -->
                 
                <h3 class="card-title">Reset your password</h3>
                <p>Enter your email address and we will send you a link to reset your password.</p>
                    
               
                <input type="email" class="form-control" name="email" placeholder="Email" required autofocus >
                <br>
                <button class="btn btn-primary btn-lg" type="submit">send email</button>
                <br>
          </form>
          <br>
        </div>

        <div class="col-sm-4">
        </div>

      </div>
    </div>
    {% endblock %}          

templates/accounts/signup.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
    <div class="container">
      <div class="row">
        
        <div class="col-sm-4">
        </div>

        <div class="col-sm-4 text-center">
          <form class="form-signin" method="post" action="{% url 'accounts:signup' %}">
            {% csrf_token %}
            <br>
            <h1 class="h3 mb-3 font-weight-normal">Please Sign up</h1>

            <input type="text" name="username" class="form-control" placeholder="Username" required >
            <br>
            <input type="email" class="form-control" name="email" placeholder="Email address" required>
            <br>
            <input type="password" name="password1" class="form-control" placeholder="Password" required>
           <br>
            <input type="password" name="password2" class="form-control" placeholder="Confirm Password" required>  
            <br>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
           <br>
          </form>
        </div>

        <div class="col-sm-4">
        </div>

      </div>
    </div>
{% endblock %}