blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import BlogPostFeed

app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', BlogPostFeed()),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap, WebsiteSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'website': StaticViewSitemap,
    'blog': BlogSitemap,
    'website': WebsiteSitemap
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
            name='django.contrib.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/',include('captcha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
     
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *



app_name = 'website'

urlpatterns = [
    
   
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('education', education_view, name='education'),
    path('experience', experience_view, name='experience'),
    path('single/<int:pid>', single_view, name='single'),
    path('skills', skills_view, name='skills'),
    path('certificates', certificates_view, name='certificates'),
    path('certificates/<str:inst_name>', certificates_view, name='certificatesinst'),
    path('newsletter', newsletter_view, name='newsletter'),
   
]

website/models.py
from django.db import models
from django.urls import reverse


# Create your models here.

class Institution(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255,  null=True, blank=True )

    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_date']
        
    def __str__(self):
        return self.name


class Certificates(models.Model):   
    image = models.ImageField(upload_to = 'blog/', default='blog/default.jpg')
    title = models.CharField(max_length=255)
    institution = models.ForeignKey(Institution, on_delete=models.SET_NULL, null=True)
    issu_date = models.DateTimeField(null=True)
    field_name = models.URLField(max_length=255, blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-issu_date']
        
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("website:single", kwargs={'pid': self.id})
    
class NewsLetter(models.Model):
    email = models.EmailField()
    
    def __str__(self):
        return self.email
    

website/forms.py
from django import forms
from website.models import contact, NewsLetter
from captcha.fields import CaptchaField
#

class NameForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    subject = forms.CharField(max_length=255)
    message = forms.CharField(widget=forms.Textarea)
    
    
class contactForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = contact
        fields = '__all__'
       # exclude = ['name']
        
        
        
        
        
class NewsletterForm(forms.ModelForm):
    
    class Meta:
        model = NewsLetter
        fields = '__all__'

website/views.py
from django.shortcuts import render,  get_object_or_404
from website.models import Certificates,Institution
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from website.forms import  contactForm, NewsletterForm
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.



def index_view(request):
    return render(request, 'website/index.html')

def about_view(request):
    return render(request, 'website/about.html')

def contact_view(request):
   if request.method == 'POST':
      form = contactForm(request.POST)
      if form.is_valid():
         #form.instance.name = 'anonymous'
         form.save()
         messages.add_message(request, messages.SUCCESS, 'we got your ticket')
         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
      else:
         messages.add_message(request, messages.ERROR, 'something went wrong')
   form = contactForm()        
   return render(request, 'website/contact.html', {'form':form})

def education_view(request):
   return render(request, 'website/education.html')

def experience_view(request):
   return render(request, 'website/experience.html')

def skills_view(request):
   return render(request, 'website/skills.html')

def certificates_view(request, **kwargs):
   certificates = Certificates.objects.all()    
   if kwargs.get('inst_name') != None:
      certificates = certificates.filter(institution__name=kwargs['inst_name'])
      
   
  
   context = {'certificates': certificates}
   return render(request, 'website/certificates.html', context)

def single_view(request, pid):
   certificates = Certificates.objects.all()
   certificate = get_object_or_404(certificates,pk=pid)
   
   certificates1 = list(certificates)
   for i in range(0,len(certificates1)):
      if certificates1[i].id == pid:
         if i == 0:
            previous_certificate = certificates1[i+1]
                    #print(previous_post.id)
            next_certificate = certificates1[0]
                    #print(next_post.id) 
         elif i == len(certificates1)-1:
            next_certificate = certificates1[i-1]
                    #print(next_post.id)
            previous_certificate = certificates1[len(certificates1)-1]
                    #print(previous_post.id)
         else:
           next_certificate = certificates1[i-1]
                    #print(next_post.id)  
           previous_certificate = certificates1[i+1]
                    #print(previous_post.id)    
                    
                    
   context = {'certificate': certificate,'next': next_certificate,'previous': previous_certificate,}
   
   return render(request, 'website/single.html', context)

def newsletter_view(request):
   if request.method == 'POST':
      form = NewsletterForm(request.POST)
      if form.is_valid():
         form.save()
         messages.add_message(request, messages.SUCCESS, 'We got your email')
         return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
      else:
        messages.add_message(request, messages.ERROR, 'Something went wrong') 
        

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">


				<!-- About -->
				<section id="section2">
					<div class="container">
						<h2>About Me</h2>
						<div class="row">
							<div class="col-sm-3">
								<img src="{% static 'images/man02.png' %}" alt="man" class="img-responsive section-img">
							</div> <!-- end .col-sm-3 -->
							<div class="col-sm-9">
								
								<h5>Summary</h5>
								<p> As a BI Developer with more than five years of experience, I specialize in implementing OLTP Databases and Data Warehouses, creating ETL packages using Microsoft SSIS, and writing SQL queries for reporting. My expertise extends to visualizing data through DAX and Power BI, enabling data-driven decision-making.
									I am seeking a position where I can leverage my proven SQL skills to enhance company databases and develop software for increased productivity.</p>
								<p>With 14 years of industrial experience, I have a solid understanding of processes in Production, Warehousing, Sales, Quality Assurance, Purchasing, and Planning.</p>
								<p>Additionally, I am proficient in programming languages such as Java, Python, and I am familiar with SAP and ABAP. I am also skilled in HTML, CSS, JavaScript, and Django, making me well-suited for website designing roles. My passion for new challenges and problem-solving drives my work as a Software programmer.</p>
								<div class="signature"><img src="{% static 'images/signature2.png' %}" alt="signature" class="img-responsive"></div>

								<ul class="list-unstyled text-uppercase">
									<li style="text-transform:lowercase"><b style="text-transform:uppercase" >Date Of Birth :</b>  25 Jan 1979</li>
									<li style="text-transform:lowercase"><b style="text-transform:uppercase" >Phone :</b> +971-56-808-7789</li>
									<li style="text-transform:lowercase"><b style="text-transform:uppercase" >Email :</b> bagheri.payam@gmail.com</p></li>
									<li style="text-transform:capitalize"><b style="text-transform:uppercase" >Address :</b> Cournishe Street, Sharjah, UAE.</li>
									<li style="text-transform:lowercase"><b style="text-transform:uppercase" >Website :</b> payambagheri1979.ir</li>
								</ul> <!-- end .list-unstyled -->
								<div class="spacer"></div>
								<h3>What I'm Doing</h3>
								<div class="row">
									<div class="col-sm-4">
										<div class="service">
											<div class="icon"><i class="ion-monitor"></i></div>
											<h5>Web & Design</h5>
										</div> <!-- end .service -->
									</div> <!-- end .col-sm-4 -->
									<div class="col-sm-4">
										<div class="service">
											<div class="icon"><i class="ion-monitor"></i></div>
											<h5> Development</h5>
										</div> <!-- end .service -->
									</div> <!-- end .col-sm-4 -->
									<div class="col-sm-4">
										<div class="service">
											<div class="icon"><i class="ion-monitor"></i></div>
											<h5>Data Visualization</h5>
										</div> <!-- end .service -->
									</div> <!-- end .col-sm-4 -->
								</div> <!-- end .row -->
							</div> <!-- end .col-sm-9 -->
						</div> <!-- end .row -->
					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

				

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
		{% endblock %}

templates/website/certificates.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">

				

				<!-- Portfolio -->
				<section id="section6">
					<div class="container">
						<h2>Certificates</h2>
						<div class="portfolio-wrapper">
							<div id="portfolio-filters" class="portfolio-filters">
								<a href='{% url 'website:certificates' %}'><button class="button solid-button white-purple small">Show All</button>
								<a href='{% url 'website:certificatesinst' inst_name='Linkedin' %}'><button class="button solid-button white-purple small" >Linkedin</button><a>
								<a href='{% url 'website:certificatesinst' inst_name='Maktabkhooneh' %}'><button class="button solid-button white-purple small">Maktabkhooneh</button>
								<a href='{% url 'website:certificatesinst' inst_name='RWTüV' %}'><button class="button solid-button white-purple small">RWTüV</button>
								<a href='{% url 'website:certificatesinst' inst_name='Tehran Polytechnic' %}'><button class="button solid-button white-purple small">Polytechnic</button>
							</div>
							<div id="portfolio" class="portfolio">
								{% for certificate in certificates %}
								<div class="item">
									<img src="{{ certificate.image.url }}" alt="alt text" class="img-responsive">
									<a href="{% url 'website:single' certificate.id %}" class="overlay">
										<div class="background"></div>
										<div class="meta">
											<span class="title">{{certificate.title}}</span>
											<span class="category">{{certificate.institution.name}}</span>
										</div> <!-- end .meta -->
									</a> <!-- end .overlay -->
									
								</div> <!-- end .item -->
								{% endfor %}
						</div> <!-- end .portfolio-wrapper -->
					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

				

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
		{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">


				<!-- Contact -->
				<section id="section8">
					<div class="container">
						<h2>Get In Touch With Me</h2>
						<div class="row">
							<div class="col-sm-5">
								<h5>Contact Address</h5>
								<ul class="list-icons list-unstyled">
									<li><i class="ion-ios-location-outline"></i>Corniche Street,<br />Sharjah UAE.</li>
									<li><i class="ion-iphone"></i>Phone: +971 56 808 7789</li>
									<li><i class="ion-ios-email-outline"></i>Email: <a href="mailto:bagheri.payam@gmail.com">bagheri.payam@gmail.com</a></li>
									<li><i class="ion-ios-home-outline"></i>Website: <a href="https://payambagheri1979.ir" target="_blank">payambagheri1979.ir</a></li>
								</ul>
								<div class="spacer"></div>
								<div class="social-icons">
									<a href="https://www.linkedin.com/in/bagheripayam/" class="social-icon" target="_blank"><i class="fa fa-linkedin"></i></a>
									<a href="https://github.com/payam1979" class="social-icon" target="_blank"><i class="fa fa-github"></i></a>
									<a href="https://join.skype.com/invite/syuU6iA12Phq" class="social-icon" target="_blank"><i class="fa fa-skype"></i></a>
									<a href="https://learn.microsoft.com/en-us/users/payambagheri-1444/" class="social-icon" target="_blank"><i class="fa fa-windows"></i></a>
								</div> <!-- end .social-icons -->
								<div class="spacer"></div>
							</div>
							<div class="col-sm-7">
								<h5>Contact Form</h5>
								
								<form action="{% url 'website:contact' %}" method="post" class="form-horizontal contact-form">
									{% csrf_token %}
									<div class="form-group">
										
										<label class="col-sm-2 control-label">Name</label>
										<div class="col-sm-10">
											<input type="text" class="contact-name" name="name" required="" />
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									<div class="form-group">
										<label class="col-sm-2 control-label">Email</label>
										<div class="col-sm-10">
											<input type="email" class="contact-email" name="email" required="" />
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									<div class="form-group">
										<label class="col-sm-2 control-label">Subject</label>
										<div class="col-sm-10">
											<input type="text" class="contact-name" name="subject" />
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									<div class="form-group">
										<label class="col-sm-2 control-label">Message</label>
										<div class="col-sm-10">
											<textarea name="message" class="message" rows="3" required=""></textarea>
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									
									<div class="form-group">
										<div class="col-sm-10 col-sm-offset-2">
											{{ form.captcha}}
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									<div class="form-group">
										<div class="col-sm-10 col-sm-offset-2">
											<button type="submit" class="button solid-button purple">Send Message</button>
										</div> <!-- end .col-sm-10 -->
									</div> <!-- end .form-group -->
									<div class="contact-loading alert alert-info form-alert">
										<span class="message">Loading...</span>
										<button type="button" class="close" data-hide="alert" aria-label="Close"><i class="fa fa-times"></i></button>
									</div>
									<div class="contact-success alert alert-success form-alert">
										<span class="message">Success!</span>
										<button type="button" class="close" data-hide="alert" aria-label="Close"><i class="fa fa-times"></i></button>
									</div>
									<div class="contact-error alert alert-danger form-alert">
										<span class="message">Error!</span>
										<button type="button" class="close" data-hide="alert" aria-label="Close"><i class="fa fa-times"></i></button>
									</div>
									
								</form> <!-- end contact-form -->
							</div>
						</div>
						
					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
	{% endblock %}

templates/website/education.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">


				<!-- Education -->
				<section id="section5">
					<div class="container">
						<h2>Educational Value</h2>
						
							<div class="item">
								
								<div class="content">
									
									<div class=" row">
										<div class="  col-sm-6">
											<h4><a href='{% url 'website:certificatesinst' inst_name='Tehran Polytechnic' %}'>Materials and Metallurgical Engineering</a></h4>
											<p><a href='{% url 'website:certificatesinst' inst_name='Tehran Polytechnic' %}'>Bachelor's Degree</a> </p>
											<p>Amirkabir University of Technology</p>
											<p>(Tehran Polytechnic)</p>
											<p>1997 - 2002 </p>
										</div>
										<div class="  col-sm-6">
											<a href='https://en.wikipedia.org/wiki/Amirkabir_University_of_Technology' target="_blank"><img  src='{% static 'images/R.png' %}' alt="" /></a>
										</div>
									</div>
								</div>
								
							</div> <!-- end item -->
							
							
							
																						

						<h2>Hobbies & Interest</h2>
						<div class="row">
							<div class="col-sm-2 col-sm-offset-1 col-xs-6">
								<div class="icon-box">
									<div class="icon"><i class="ion-easel"></i></div>
									<h6>Web Research</h6>
								</div> <!-- end .icon-box -->
							</div> <!-- end .col-sm-2 -->
							<div class="col-sm-2 col-xs-6">
								<div class="icon-box">
									<div class="icon"><i class="ion-ios-camera-outline"></i></div>
									<h6>Photography</h6>
								</div> <!-- end .icon-box -->
							</div> <!-- end .col-sm-2 -->
							<div class="col-sm-2 col-xs-6">
								<div class="icon-box">
									<div class="icon"><i class="ion-plane"></i></div>
									<h6>Travelling</h6>
								</div> <!-- end .icon-box -->
							</div> <!-- end .col-sm-2 -->
							<div class="col-sm-2 col-xs-6">
								<div class="icon-box">
									<div class="icon"><i class="ion-ios-bookmarks-outline"></i></div>
									<h6>Book Reading</h6>
								</div> <!-- end .icon-box -->
							</div> <!-- end .col-sm-2 -->
							<div class="col-sm-2 col-xs-6">
								<div class="icon-box">
									<div class="icon"><i class="ion-ios-musical-notes"></i></div>
									<h6>Music</h6>
								</div> <!-- end .icon-box -->
							</div> <!-- end .col-sm-2 -->
						</div> <!-- end .row -->
					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

				

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
		{% endblock %}

templates/website/experience.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">

			

				<!-- Experience -->
				<section id="section4">
					<div class="container">
						<h2>20 Years Experience</h2>
						<div class="experience-timeline">
							<div class="experience-block clearfix">
								<div class="meta">
									<span class="year">2022 - Current</span>
									<span class="company">Premium Technical Support (PTS), Dubai, UAE</span>
								</div> <!-- end .meta -->
								<div class="content">
									<h5>BI Developer & SQL Server Expert</h5>
									<p>This Company established in 2011 with the aim of providing products and services in the field of Technology
										<h5>Key Responsibilities:</h5>
										<ul>
										  <li>Redesign databases.</li>
										  <li>Design OLTP Data Model and Create SQL Objects, Tables, Procedures, etc.</li>
										  <li>Design ETL packages with SSIS and fill Data in the Data warehouse, Customize DWH Tables.</li>
										  <li>Create business reports with SQL Query and Power BI.</li>
										</ul>
						
										<h5>Key achivments:</h5>
										<ul>
										  <li>Redesigned databases for better due to making data usable.</li>
										  <li>Created more than 10 reports and dashboards using DAX and Power BI.</li>
										</ul>

									</p>
								</div> <!-- end .content -->
								<div class="icon">
									<i class="ion-calendar"></i>
								</div> <!-- end .icon -->
								<div class="line"></div>
							</div> <!-- end .experience-block -->
							<div class="experience-block clearfix">
								<div class="meta">
									<span class="year">2018 - 2022</span>
									<span class="company">Soshiance, Tehran, Iran</span>
								</div> <!-- end .meta -->
								<div class="content">
									<h5>BI Developer & SQL Server Expert</h5>
									<p>This Company established in 2003 with the aim of providing products and services in the field of Information and Communication Technology.
										<h5>Key Responsibilities:</h5>
										<ul>
										  <li>Work closely with clients, Analyze customer business requirements, gathering and processing.</li>
										  <li>Design OLTP Data Model and Create SQL Objects, Tables, Procedures, etc.</li>
										  <li>Design ETL packages with SSIS and fill Data in the Data warehouse, Customize DWH Tables.</li>
										  <li>Create business reports with SQL Query and Power BI.</li>
										</ul>
						
										<h5>Key achivments:</h5>
										<ul>
										  <li>Designed 5+ databases for new products (coordinated with the software developer team) due to client’s needs.</li>
										  <li>Converted 20+ reports from other systems into SSRS.</li>
										  <li>Trained 5+ business users in data modeling in Power BI for creating reports.</li>
										  <li>Created 50+ reports using Power BI.</li>
										  <li>Redesigned 5+ older dashboards to improve performance and decrease the time of analysis.</li>
										</ul>

									</p>
								</div> <!-- end .content -->
								<div class="icon">
									<i class="ion-calendar"></i>
								</div> <!-- end .icon -->
								<div class="line"></div>
							</div> <!-- end .experience-block -->
							<div class="experience-block clearfix">
								<div class="meta">
									<span class="year">2014 - 2018</span>
									<span class="company">Poomar, Markazi, Iran</span>
								</div> <!-- end .meta -->
								<div class="content">
									<h5>Production Line Expert</h5>
									<p>This company founded in 1972 with the aim of manufacturing stationery and office furniture.
										<h5>Key Responsibilities:</h5>
										<ul>
										<li>Analyzing customer requirements, Design and manage each project individually.</li>
										<li>Device repair and maintenance management.</li>
										<li>Visiting the installation projects. (Office furniture).</li>
										<li>Training of construction and installation personnel.</li>
										<li>Calculate the costs of each project separately and notify the CEO.</li>
										</ul>

										<h5>Key achivments:</h5>
										<ul>
										<li>Reduced production costs by increasing the productivity of labor.</li>
										<li>Reduced production waste by reviewing and redesigning products.</li>
										<li>Reduced product delivery time to the customer with full supervision from design to production and delivery.</li>
										</ul>

									</p>
								</div> <!-- end .content -->
								<div class="icon">
									<i class="ion-calendar"></i>
								</div> <!-- end .icon -->
								<div class="line"></div>
							</div> <!-- end .experience-block -->
							<div class="experience-block clearfix">
								<div class="meta">
									<span class="year">2006 - 2014</span>
									<span class="company">FaraNiroo Sazeh, Alborz, Iran</span>
								</div> <!-- end .meta -->
								<div class="content">
									<h5>Product Manager</h5>
									<p>This company was founded in 2005 with the aim of manufacturing various types of anchor bolts, patterns, various bolts and nuts (galvanized and phosphate), tray and ladder of cable and other apparatuses as required by industries.
              
										<h5>Key Responsibilities:</h5>
										<ul>
										<li>Analyzing customer requirements, gathering and managing the whole project.</li>
										<li>Find or build new technologies for this category.</li>
										<li>Analysis and review of accounting and warehousing.</li>
										<li>Recruitment and training of personnel.</li>
										<li>Prepare and submit reports to the board</li>
										</ul>

										<h5>Key achivments:</h5>
										<ul>
										<li>Construction of all structures required for power substations up to 400kw capacity.</li>
										<li>Construction of all required structures for more than 20 electrical substations.(63-230-400).</li>
										</ul>
									</p>
								</div> <!-- end .content -->
								<div class="icon">
									<i class="ion-calendar"></i>
								</div> <!-- end .icon -->
								<div class="line"></div>
							</div> <!-- end .experience-block -->
							<div class="experience-block clearfix">
								<div class="meta">
									<span class="year">2004 - 2006</span>
									<span class="company">Nasoozmehr, Alborz, Iran</span>
								</div> <!-- end .meta -->
								<div class="content">
									<h5>Quality Assurance Manager</h5>
									<p>This company established in 1998 with the aim of producing industrial parts from alloy steels. Company produces all kinds of low-alloy; high-alloy and non-alloy steel products with the use of experienced and expert workers as well as advanced equipment in compliance with international standards and guarantees the satisfaction of its customers.
              
										<h5>Key Responsibilities:</h5>

										<ul>
										<li>Design and creation of quality management system.</li>
										<li>Follow up on quality management system requirements.</li>
										<li>Audit of quality management system.</li>
										</ul>

										<h5>Key achivments:</h5>
										<ul>
										<li>We have succeeded in obtaining the ISO 9000 certification.</li>
										</ul>
									</p>
								</div> <!-- end .content -->
								<div class="icon">
									<i class="ion-calendar"></i>
								</div> <!-- end .icon -->
								
							</div> <!-- end .experience-block -->
						</div> <!-- end .experience-timeline -->

						<!-- Testimonials -->
						<div class="row">
							<div class="col-sm-8 col-sm-offset-2">
								<div class="testimonial-slider owl-carousel">
									
								</div> <!-- end .testimonial-slider -->
							</div> <!-- end .col-sm-8 -->
						</div> <!-- end .row -->

					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

			

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
	{% endblock %}

templates/website/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">
				<div class="container">
					<div class="row d-flex align-items-center justify-content-center">
						 <div class="about-content col-lg-12">
							
							<p class="text-white link-nav">
						  <a href="{% url 'website:index' %}">Home</a> <span class="fa fa-arrow-right"></span><a href="{% url 'website:certificates' %}">Certificates</a> <span class="fa fa-arrow-right"></span> <span>{{certificate.title}}</span>
							</p>
					  </div>
					</div>
			  </div>

				<!-- Single Portfolio -->
				<section class="active">
					<div class="container">
						<div class="row">
							<div class="col-sm-8">
								<div class="portfolio-details ">
									
									<div><img src='{{certificate.image.url}}' alt="alt text" class="img-responsive"></div>
									
									
								</div> <!-- end .portfolio-slider -->
								
							</div> <!-- end .col-sm-8 -->
							<div class="col-sm-4">
								
								<div class="portfolio-details">
									<h4>{{certificate.title}}</h4>
									<div class="portfolio-meta">
										<span>Date:</span>
										{{certificate.issu_date|date:'d M Y'}}
									</div> <!-- end .portfolio-meta -->
									
									<div class="portfolio-meta">
										<span>Institution:</span>
										{{certificate.institution.name}}
									</div> <!-- end .portfolio-meta -->
									<!-- <div class="portfolio-meta">
										<span>Type:</span>
										Branding, Illustrator
									</div> --> <!-- end .portfolio-meta -->
									<p><a href="{{certificate.field_name}}" target="_blank" class="button solid-button purple">Visit Website</a></p>
								</div> <!-- end .portfolio-details -->
								<div class="footer">
									<p class="button-row blog-button-row">
										{% if previous.id != certificate.id %}
										<a href="{% url 'website:single' previous.id %}" class="button solid-button light">Prev</a>
										{% else %}
										<a href="#" class="button solid-button purple">First</a>
										{% endif %}
										{% if next.id != certificate.id %}
										<a href="{% url 'website:single' next.id %}" class="button solid-button light">Next</a>
										{% else %}
										<a href="#" class="button solid-button purple">Last</a>
										{% endif %}
									</p>
								</div>
							</div> <!-- end .col-sm-4 -->
						</div> <!-- end .row -->
					</div> <!-- end .container -->
				</section> <!-- end #section1 -->

			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
		{% endblock %}