blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import BlogPostFeed

app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', BlogPostFeed()),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap, WebsiteSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'website': StaticViewSitemap,
    'blog': BlogSitemap,
    'website': WebsiteSitemap
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
            name='django.contrib.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/',include('captcha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
     
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *



app_name = 'website'

urlpatterns = [
    
   
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('education', education_view, name='education'),
    path('experience', experience_view, name='experience'),
    path('single/<int:pid>', single_view, name='single'),
    path('skills', skills_view, name='skills'),
    path('certificates', certificates_view, name='certificates'),
    path('certificates/<str:inst_name>', certificates_view, name='certificatesinst'),
    path('newsletter', newsletter_view, name='newsletter'),
   
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class Post(models.Model):
    image = models.ImageField(upload_to = 'blog/', default='blog/default.jpg')
    image_home = models.ImageField(upload_to = 'blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags =TaggableManager()
    category =models.ManyToManyField(Category)
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(null=True)
    
    class Meta:
        ordering = ['-published_date']
        #indexes = [models.Index(fields=['published_date'])]
        #verbose_name = 'پست'
        #verbose_name_plural = 'پست ها'
        
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("blog:single", kwargs={'pid': self.id})
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_date']
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Post, Comment
#from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    #captcha = CaptchaField()
    class Meta:
        model = Comment
        
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from blog.forms import CommentForm
from django.contrib import messages
from blog.models import Post, Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from blog.models import *

# Create your views here.

def blog_view(request, **kwargs):
   
    posts = Post.objects.exclude(published_date__gt=timezone.now()).exclude (status= 0)    
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
        
    posts = Paginator(posts,3)
    
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)  
    except EmptyPage:
        posts = posts.get_page(1)
        
    
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

#def blog_single(request, pid):
    #post = get_object_or_404(Post, pk=pid)
    #context = {'post':post}
    #return render(request, 'blog/single-blog-post.html', context)

def blog_single(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'we got your comment')
        else:
            messages.add_message(request, messages.ERROR, 'something went wrong')
    posts = Post.objects.exclude(published_date__gt=timezone.now()).exclude(status= 0)
    post = get_object_or_404(posts,pk=pid)
    comment = Comment.objects.filter(post=post.id, approved=True)
    if request.user.is_authenticated:
        post.counted_view +=1
        post.save()
        post1 = list(posts)
        post2 = list()
        form = CommentForm()        
        for i in range(0,len(post1)):
            if post1[i].id == pid:
                if i == 0:
                    previous_post = post1[i+1]
                        #print(previous_post.id)
                    next_post = post1[0]
                        #print(next_post.id) 
                elif i == len(post1)-1:
                    next_post = post1[i-1]
                        #print(next_post.id)
                    previous_post = post1[len(post1)-1]
                        #print(previous_post.id)
                else:
                    next_post = post1[i-1]
                        #print(next_post.id)  
                    previous_post = post1[i+1]
                        #print(previous_post.id)                        
            #print(next_post, post, previous_post)   
        context = {'post': post,
                        'form': form,
                        'comment': comment,
                        'next': next_post,
                        'previous': previous_post,}
                    
        return render(request, 'blog/single-blog-post.html', context)
    elif not request.user.is_authenticated:
        post.counted_view +=1
        post.save()
        post1 = list(posts)
        post2 = list()
        form = CommentForm()
        if not post.login_require:
            
            for i in range(0,len(post1)):
                if  post1[i].login_require == False:
                    post2.append(post1[i])
           # print(post2)
            for i in range(0,len(post2)):
                if post2[i].id == pid:
                    if i == 0:
                        previous_post = post2[i+1]
                        next_post = post2[0]
                    elif i == len(post2)-1:
                        next_post = post2[i-1]
                        previous_post = post2[len(post2)-1]
                    else:
                        next_post = post2[i-1]
                        previous_post = post2[i+1]
            context = {'post': post,
                            'form': form,
                            'comment': comment,
                            'next': next_post,
                            'previous': previous_post,}
            return render(request, 'blog/single-blog-post.html', context)   
        else:
            return HttpResponseRedirect(reverse('accounts:login'))
        
        
def blog_search(request):
    posts = Post.objects.exclude(published_date__gt=timezone.now()).exclude (status= 0)
    if request.method == 'GET':
        if s:= request.GET.get('s'):
            posts = posts.filter(content__contains=s)
            count = len(posts)
            if count > 0:
                mes = 'Found' + str(count) + 'posts for your search'
                messages.add_message(request, messages.SUCCESS, mes)
            
            else:
                messages.add_message(request, messages.ERROR, 'Nothing in posts maches your search')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                
    
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block content %}
  
<div>
	<br>
	<br>
	<br>
</div>

  <!-- Start post-content Area -->
  <section class="post-content-area">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 posts-list">
          {% for post in posts %}
            <div class="single-post row">
              <div class="col-lg-3 col-md-3 meta-details">
                
                <div class="user-details row">
                  <p class="user-name col-lg-12 col-md-12 col-6">
                    <a href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.get_full_name }}</a> <span class="lnr lnr-user"></span>
                  </p>
                  <p class="date col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.published_date|date:'D d M Y' }}</a> <span class="lnr lnr-calendar-full"></span>
                  </p>
                  <p class="view col-lg-12 col-md-12 col-6">
                    <a href="#">{{ post.counted_view }} Views</a> <span class="lnr lnr-eye"></span>
                  </p>
                  <p class="comments col-lg-12 col-md-12 col-6">
                    <a href="{% url 'blog:single' post.id %}">{% comment_count post.id %} Comments</a> <span class="lnr lnr-bubble"></span>
                  </p>
				  <ul class="tags">
					<!-- {{ post.category.all|join:", "}} -->
					{% for cat in post.category.all %}
					<a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
					{% endfor %}
				  </ul>
                </div>
              </div>
              <div class="col-lg-9 col-md-9">
                <div class="feature-img">
                  <a href="{% url 'blog:single' post.id %}"><img src="{{ post.image_home.url }}" alt="" class="img-responsive"/></a>
                </div>
                <a class="posts-title" href="{% url 'blog:single' post.id %}"><h3>{{ post.title }}</h3></a>
                <p class="excert">{{ post.content|safe|truncatewords:10 }}</p>
                <hr>
              </div>
            </div>
		<hr>
          {% endfor %}

		  
          <nav class="blog-pagination justify-content-center d-flex">
            <ul class="pagination">
              {% if posts.has_previous %}
                <li class="page-item">
                  <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous"><span aria-hidden="true"><span class="fa fa-chevron-left"></span></span></a>
                </li>
              {% endif %}
              {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                  <li class="page-item active">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                  </li>
                {% else %}
                  <li class="page-item">
                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                  </li>
                {% endif %}
              {% endfor %}
              {% if posts.has_next %}
                <li class="page-item">
                  <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next"><span aria-hidden="true"><span class="fa fa-chevron-right"></span></span></a>
                </li>
              {% endif %}
            </ul>
          </nav>
        </div>
        <div class="col-lg-4 sidebar-widgets">
          <div class="widget-wrap">
            

            {% include 'blog/blog-writer.html' %}

            {% categories %}
            {% popularpost 3 %}
            {% include 'blog/blog-newsletter.html' %}

            

           <!--  {% include 'blog/blog-tags.html' %} -->
          </div>
        </div>
      </div>
    </div>
  </section>
  

    
  <!-- End post-content Area -->
{% endblock %}

templates/blog/blog-latest.html
{% load static %}
{% load blog_tags %}


    <div class="row d-flex justify-content-center">
      
          <h4 class="mb-10">Latest from My Blog</h4>
          
        
    </div>

    <div class="row">
      <div class="active-recent-blog-carusel">
        {% for post in posts %}
          <div class="single-recent-blog-post item">
            <div class="thumb">
              <img class="img-fluid" src="{{ post.image.url }}" style = "height: 50px; width: 50px;" alt="" />
            </div>
            <div class="details">
              
              <a href="{% url 'blog:single' pid=post.id %}"><h6>{{ post.title }}<span class="fa fa-hand-o-right"></span>{{ post.published_date|date:'jS F, Y' }}</h6></a>
            
              
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
 

templates/blog/blog-newsletter.html
{% load static %}
<div class="single-sidebar-widget newsletter-widget">
  <div class="signature"></div>
    <h4 class="newsletter-title">Newsletter</h4>
    <p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>
   
    <form  action="{% url 'website:newsletter' %}" method="post" class="subscription relative">
      {% csrf_token %}
    <div class="form-group d-flex flex-row">
      <div class="col-autos">
        <div class="input-group">
          <div class="input-group-prepend">
            <div class="input-group-text">
              <i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
          </div>
       
            
              
              <input name="email" type="email" class="form-control"  placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" required=""/>
              <button type='submit' class="bbtns">Subcribe</button>
           
          
          
        </div>
      </div>
      
    </div>
  </form>
    
    
  </div>

templates/blog/blog-popular.html
{% load static %}
{% load blog_tags %}
{% load humanize %} 
<div class="single-sidebar-widget popular-post-widget">
  <h4 class="popular-title">Most Popular Posts</h4>
  <div class="popular-post-list">
    {% for post in posts1 %}
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img class="img-fluid"  src="{{ post.image_home.url }}" style = "height: 50px; width: 50px;" alt="" />
        
          <a href="{% url 'blog:single' pid=post.id %}"><h6>{{ post.title }}<span class="fa fa-hand-o-right"></span>{{ post.published_date|naturaltime }}</h6></a>
            
        </div>
        <hr>
      </div>
      
    {% endfor %}
    
  </div>
</div>

templates/blog/blog-post-categories.html
{% load static %}
{% load blog_tags %}

<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">
    {% for name, count in categories.items %}
      <li>
        <div class="d-flex justify-content-between">
        <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
          <span>{{ name }}</span></a>
          <span>{{ count }}</span>
        </div>
      </li>
    {% endfor %}
  </ul>
  <div class="signature"></div>
</div>

templates/blog/blog-tags.html
{% load static %}

<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
      {% for tag in post.tags.all %}
      <li>
        <a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a>
      </li>  
         {% endfor %}
    </ul>
  </div>

templates/blog/blog-writer.html
{% load static %}

<div class="single-sidebar-widget user-info-widget">
  <br>
  <br>
  <img src="{% static 'images/man010.png' %}" alt="pbp" />
  <a href="{% url 'website:about' %}"><h4>Payam Bagheri Papkiadeh</h4></a>
  <p>Developer</p>
  
  
  <div class="signature"></div>
</div>

templates/blog/single-blog-post.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block content %}


		<!-- Sections -->
		<div class="sections">
			<div class="sections-wrapper clearfix">
			<div class="overlay overlay-bg"></div>
    			<div class="container">
     				 <div class="row d-flex align-items-center justify-content-center">
       					<div class="about-content col-lg-12">
          					
          					<p class="text-white link-nav">
            				<a href="{% url 'website:index' %}">Home</a> <span class="fa fa-arrow-right"></span><a href="{% url 'blog:index' %}">Blog</a> <span class="fa fa-arrow-right"></span> <span>{{post.title}}</span>
          					</p>
        				</div>
      				</div>
    			</div>


			
				
				
				<!--Single Blog Post -->
				<section>


					<div class="container">
						<div class="single-blog-post">


							<header class="blog-header clearfix">
								<div class="content">
									<!--<span class="date">March 11, 2015</span>-->
									<h4>{{post.title}}</h4>
									<!--<span class="meta"><a href="">7 Comments</a> | <a href="">By Admin</a></span> -->
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'website:about' %}">{{post.author.get_full_name}}</a> <span class="fa fa-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date|date:'D, d M Y'}}</a> <span class="fa fa-calendar"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} views</a> <span class="fa fa-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comment_count post.id %} Comments</a> <span class="fa fa-comments"></span></p>	
										
											<span><ul class="tags">
												<!-- {{ post.category.all|join:", "}} -->
												{% for cat in post.category.all %}
												  <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>{% if not forloop.last %},{% endif %}
												{% endfor %}
											  </ul></span>
											<br>
											<br>																			
									</div>
									<div class="footer">
										<p class="button-row blog-button-row">
											{% if previous.id != post.id %}
											<a href="{% url 'blog:single' previous.id %}" class="button solid-button light">Prev</a>
											{% else %}
											<a href=""{% url 'blog:single' post.id %}"" class="button solid-button purple">First</a>
											{% endif %}
											{% if next.id != post.id %}
											<a href="{% url 'blog:single' next.id %}" class="button solid-button light">Next</a>
											{% else %}
											<a href=""{% url 'blog:single' post.id %}"" class="button solid-button purple">Last</a>
											{% endif %}
										</p>
									</div>
								</div> <!-- end .content -->
								<div class="image" ><img  src='{{post.image.url}}' alt="" class="img-responsive" /></div>
							</header> <!-- end .blog-header -->


							<div class="blog-post">
								<div class="blog-post-content">
									<p>{{ post.content|safe }}</p>
									
								</div> <!-- end .blog-post-content -->




								<div class="blog-post-comments">
									<h4>{{ comment|length }} Comments</h4>
									{% for comment1 in comment %}

									<div class="comment">
										<div class="inner clearfix">
											<div class="image"><img src="{% static 'images/comment.png' %}" alt="alt text" class="img-responsive"></div>
											<div class="content">
												<h5>{{comment1.name}}</h5>
												<span class="meta">{{comment1.created_date|naturalday}}</span>
												<h6>{{comment1.subject}}</h6>
												<p>{{comment1.message}}</p>
												
												
											</div> <!-- end .content -->
										</div> <!-- end .inner -->
										
									</div> <!-- end .comment -->

									{% empty %}
									<p>No Comment yet, Be the First</p>
									{% endfor %}

								</div> <!-- end .blog-post-comments -->




								<div class="leave-comment">
									<h4>Leave A Comment</h4>
									<div class="inner">
										

										<form action="{% url 'blog:single' pid=post.id %}" method="post" class="form-horizontal">
											{% csrf_token %}
											<input type="hidden" name="post" value="{{post.id}}">
											{% if request.user.is_authenticated %}
											<input type="hidden" name="name" value="{{request.user.username}}">
											<input type="hidden" name="email" value="{{request.user.email}}">
											{% else %}
											<div class="form-group">
												<label class="col-sm-2 control-label">Name</label>
												<div class="col-sm-10">
													<input type="text" class="contact-name" name="name" required="" />
												</div> <!-- end .col-sm-10 -->
											</div> <!-- end .form-group -->
											<div class="form-group">
												<label class="col-sm-2 control-label">Email</label>
												<div class="col-sm-10">
													<input type="email" class="contact-email" name="email" required=""/>
												</div> <!-- end .col-sm-10 -->
											</div> <!-- end .form-group -->
											{% endif %}
											<div class="form-group">
												<label class="col-sm-2 control-label">Subject</label>
												<div class="col-sm-10">
													<input type="text" class="contact-name" name="subject" />
												</div> <!-- end .col-sm-10 -->
											</div> <!-- end .form-group -->

											<div class="form-group">
												<label class="col-sm-2 control-label">Message</label>
												<div class="col-sm-10">
													<textarea name="message" class="contact-message" rows="3" required=""></textarea>
												</div> <!-- end .col-sm-10 -->
											</div> <!-- end .form-group -->
											<div class="form-group">
												<div class="col-sm-10 col-sm-offset-2">
													<button type="submit" class="button solid-button purple">Post Comment</button>
												</div> <!-- end .col-sm-10 -->
											</div> <!-- end .form-group -->
										</form>
									</div> <!-- end .inner -->
								</div> <!-- end .leave-comment -->



							</div> <!-- end .blog-post -->




							<div class="blog-details">
								{% include 'blog/blog-writer.html' %}


								<!-- <div class="section">
									<h5>Share Post</h5>
									<div class="social-icons">
										<a href="" class="social-icon"><i class="fa fa-facebook"></i></a>
										<a href="" class="social-icon"><i class="fa fa-twitter"></i></a>
										<a href="" class="social-icon"><i class="fa fa-google-plus"></i></a>
										<a href="" class="social-icon"><i class="fa fa-behance"></i></a>
										<a href="" class="social-icon"><i class="fa fa-dribbble"></i></a>
									</div> --><!-- end .social-icons -->
								<!--</div>--> <!-- end .section -->


								<div class="">
									{% include 'blog/blog-tags.html' %}
								</div> <!-- end .section -->
								<div class="signature"></div>

								{% popularpost 2 %}
								
							</div> <!-- end .blog-details -->



						</div> <!-- end .single-blog-post -->
					</div> <!-- end .container -->
				</section>
				


			</div> <!-- end .sections-wrapper -->
		</div> <!-- end .sections -->
		
		{% endblock %}