accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # login
    path('login/', views.login_view, name='login'),
    #logout
    path('logout', views.logout_view, name='logout'),
    #registration
    path('signup', views.signup_view, name='signup'),
    
    path('change/password',views.ChangePasswordView.as_view(),name="change-password"),
    path('password_reset', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),

]

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import BlogPostFeed

app_name = 'blog'

urlpatterns = [
    path('',blog_view, name='index'),
    path('single/<int:pid>', blog_single, name='single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed', BlogPostFeed()),
   
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from website.sitemaps import StaticViewSitemap, WebsiteSitemap
from blog.sitemaps import BlogSitemap


sitemaps = {
    'website': StaticViewSitemap,
    'blog': BlogSitemap,
    'website': WebsiteSitemap
    }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps},
            name='django.contrib.views.sitemap'),
    path('robots.txt',include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/',include('django_summernote.urls')),
    path('captcha/',include('captcha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
   
     
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *



app_name = 'website'

urlpatterns = [
    
   
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('education', education_view, name='education'),
    path('experience', experience_view, name='experience'),
    path('single/<int:pid>', single_view, name='single'),
    path('skills', skills_view, name='skills'),
    path('certificates', certificates_view, name='certificates'),
    path('certificates/<str:inst_name>', certificates_view, name='certificatesinst'),
    path('newsletter', newsletter_view, name='newsletter'),
   
]

templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Payam Bagheri</title>
		<link rel="shortcut icon"  href="{% static 'favicon.ico' %}"/>
		<!-- Bootstrap -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!-- Material Design Icons -->
		<link href="{% static 'fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet">
		<!-- Font Awesome -->
		<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- Ionicons -->
		<link href="{% static 'fonts/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
		<!-- Owl Carousel -->
		<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'css/owl.theme.default.css' %}" rel="stylesheet">
		<!-- Style.css -->
		<link href="{% static 'css/style.css' %}" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>

		<!-- Search -->
		<div class="search-overlay"></div>
		<div class="search">
			<a href="" class="search-close"><i class="md md-close"></i></a>
			<div class="row">
				<div class="col-sm-6 col-sm-offset-3">
					<h4>Just Start Typing Text and Press Enter</h4>
					<form class="search-form" action="{% url 'blog:search' %}">
						<input placeholder="Search Posts" type="text" id="search" name="s" class="text-center" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
					</form> <!-- end .search-form -->
				</div> <!-- end .col-sm-6 -->
			</div> <!-- end .row -->
		</div> <!-- end .row -->
		<!-- Slide Out -->
		<div class="slide-out-overlay"></div>
		<div class="slide-out">
			<header class="slide-out-header clearfix">
				<div class="clearfix">
					<a href="" class="slide-out-close pull-left"><i class="md md-close"></i></a>
					<a href="" class="open-search pull-right"><i class="md md-search"></i></a>
					<a href="" class="slide-out-share pull-right"><i class="md md-more-vert"></i></a>
				</div> <!-- end .clearfix -->
				<!-- Popup -->
				
				<div class="image"><img src="{% static 'images/head01.png' %}" alt="alt text" class="img-responsive"></div>
				<div class="content">
					<h5>Payam Bagheri</h5>
					<span>Developer</span>
				</div> <!-- end .content -->
				<div class="text-right">
					<a href={% static '/myfiles/CV.pdf' %} download class="button link-button white icon-left"><i class="md md-file-download"></i>Download Resume</a>
				</div> <!-- end .text-right -->
			</header> <!-- end .slide-out-header -->
			<div class="slide-out-widgets">
				<div class="slide-out-widget">
					
					{% latestposts 4 %}
				</div> <!-- end .slide-out-widget -->
				<div class="slide-out-widget">
					
				</div> <!-- end .slide-out-widget -->
			</div> <!-- end .slide-out-widgets -->
		</div> <!-- end .slide-out -->

		<!-- Header -->
		<header class="header">
			<div class="top clearfix">
				
					<div class="row align-items-center">
					  <div class="col-lg-6 col-sm-6 col-6 header-top-left">
						<ul>
						  {% if request.user.is_authenticated %}
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="#" >Logged in as {{ request.user.username }}</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:logout' %}" >Logout</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:change-password' %}" >Change password</a>
						  </li>
						  {% else %}
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:login' %}">Login</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:signup' %}">Signup</a>
						  </li>
						  {% endif %}
						</ul>
					  </div>
					  <div class="col-lg-6 col-sm-6 col-6 header-top-right">
						<div class="right-icons">
							<a href="" class="open-search header-open-search"><i class="md md-search"></i></a>
						</div> <!-- end .right-icons -->
						<!-- Popup -->
					  </div>
					</div>
				  




				
				
			</div> <!-- end .top -->
			<div class="bottom clearfix">
				<div class="title"><img class="mb-4" src="{% static 'images/logo1.png' %}" alt="" width="72" height="72"></div>
				<div class="header-action-button-wrapper">
					<a href="" class="header-action-button action-button"><i class="md md-add"></i></a>
				</div> <!-- end .header-action-button-wrapper -->
				<a href="" class="responsive-menu-open">Menu <i class="fa fa-bars"></i></a>
				<nav class="main-nav">
					<ul class="list-unstyled">
						<li><a href="{% url 'website:index' %}">Home</a></li>
						<li><a href="{% url 'website:about' %}">About</a></li>
						<li><a href="{% url 'website:skills' %}">Skill</a></li>
						<li><a href="{% url 'website:experience' %}">Experience</a></li>
						<li><a href="{% url 'website:education' %}">Education</a></li>
						<li><a href="{% url 'website:certificates' %}">Certificates</a></li>
						<li><a href="{% url 'blog:index' %}">Blog</a></li>
						<li><a href="{% url 'website:contact' %}">Contact</a></li>
					</ul>
				</nav> <!-- end .main-nav -->
			</div> <!-- end .bottom -->
		</header> <!-- end .header -->
		<div class="responsive-menu">
			<a href="" class="responsive-menu-close">Close <i class="ion-android-close"></i></a>
			<nav class="responsive-nav"></nav> <!-- end .responsive-nav -->
		</div> <!-- end .responsive-menu -->

		{% block content %}

		{% endblock %}
	

		
		
		<!-- Footer -->
		<footer class="footer">
			<div class="top">
				<div class="container">
					<div class="row">
						<div class="col-sm-4">
							<h4>Address</h4>
							<p>Corniche Street,<br />Sharjah UAE.</p>
						</div> <!-- end .col-sm-4 -->
						<div class="col-sm-4">
							<h4>Connect</h4>
							<div class="social-icons">
								<a href="https://www.linkedin.com/in/bagheripayam/" class="social-icon" target="_blank"><i class="fa fa-linkedin"></i></a>
								<a href="https://github.com/payam1979" class="social-icon" target="_blank"><i class="fa fa-github"></i></a>
								<a href="https://join.skype.com/invite/syuU6iA12Phq" class="social-icon" target="_blank"><i class="fa fa-skype"></i></a>
								<a href="https://learn.microsoft.com/en-us/users/payambagheri-1444/" class="social-icon" target="_blank"><i class="fa fa-windows"></i></a>
								
								
							</div> <!-- end .social-icons -->
						</div> <!-- end .col-sm-4 -->
						<div class="col-sm-4">
							<h4>Contact</h4>
							<p>Tel: +971 56-808-7789<br />Mail: <a href="mailto:bagheri.payam@gmail.com">bagheri.payam@gmail.com</a></p>
						</div> <!-- end .col-sm-4 -->
					</div> <!-- end .row -->
				</div> <!-- end .container -->
			</div> <!-- end .footer -->
			<div class="bottom">Copyright &copy; P_B_P. All Rights Reserved.</div> <!-- end .bottom -->
		</footer> <!-- end .footer -->
		{% if messages %}
		{% for message in messages %}
		<script>alert('{{message}}');</script>
		{% endfor %}
		{% endif %}
		<!-- jQuery -->
		<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
		<!-- Bootstrap -->
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<!-- Inview -->
		<script src="{% static 'js/jquery.inview.min.js' %}"></script>
		<!-- SmoothScroll -->
		<script src="{% static 'js/smoothscroll.js' %}"></script>
		<!-- jQuery Knob -->
		<script src="{% static 'js/jquery.knob.min.js' %}"></script>
		<!-- Owl Carousel -->
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<!-- Isotope -->
		<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
		<!-- Images Loaded -->
		<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
		<!-- google maps -->
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
		<!-- Scripts.js -->
		<script src="{% static 'js/scripts.js' %}"></script>

	</body>
</html>

templates/base1.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>

		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Payam Bagheri</title>
		<link rel="shortcut icon"  href="{% static 'favicon.ico' %}"/>
		<!-- Bootstrap -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<!-- Material Design Icons -->
		<link href="{% static 'fonts/material-design-iconic-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet">
		<!-- Font Awesome -->
		<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
		<!-- Ionicons -->
		<link href="{% static 'fonts/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
		<!-- Owl Carousel -->
		<link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
		<link href="{% static 'css/owl.theme.default.css' %}" rel="stylesheet">
		<!-- Style.css -->
		<link href="{% static 'css/style.css' %}" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

	</head>
	<body >

		
		
		<!-- Header -->
		<header class="header">
			<div class="top clearfix">
				
					<div class="row align-items-center">
					  <div class="col-lg-6 col-sm-6 col-6 header-top-left">
						<ul>
						  {% if request.user.is_authenticated %}
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="#" >Logged in as {{ request.user.username }}</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:logout' %}" >Logout</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:change-password' %}" >Change password</a>
						  </li>
						  {% else %}
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:login' %}">Login</a>
						  </li>
						  <li style="display: inline-block; margin-right: 10px;">
							<a href="{% url 'accounts:signup' %}">Signup</a>
						  </li>
						  {% endif %}
						</ul>
					  </div>
					  <div class="col-lg-6 col-sm-6 col-6 header-top-right">
						<div class="right-icons">
							<a href="" class="open-search header-open-search"></a>
						</div> <!-- end .right-icons -->
						<!-- Popup -->
					  </div>
					</div>
				  
			</div> <!-- end .top -->
			<div class="bottom clearfix">
				<div class="title"><img class="mb-4" src="{% static 'images/logo1.png' %}" alt="" width="72" height="72"></div>
				<div class="header-action-button-wrapper">
					
				</div> <!-- end .header-action-button-wrapper -->
				
				<nav class="main-nav">
					<ul class="list-unstyled">
						<li><a href="{% url 'website:index' %}">Home</a></li>
						<li><a href="{% url 'website:about' %}">About</a></li>
						<li><a href="{% url 'website:skills' %}">Skill</a></li>
						<li><a href="{% url 'website:experience' %}">Experience</a></li>
						<li><a href="{% url 'website:education' %}">Education</a></li>
						<li><a href="{% url 'website:certificates' %}">Certificates</a></li>
						<li><a href="{% url 'blog:index' %}">Blog</a></li>
						<li><a href="{% url 'website:contact' %}">Contact</a></li>
					</ul>	
				</nav> <!-- end .main-nav -->
			</div> <!-- end .bottom -->
		</header> <!-- end .header -->
		<div class="responsive-menu">
			<a href="" class="responsive-menu-close">Close <i class="ion-android-close"></i></a>
			<nav class="responsive-nav"></nav> <!-- end .responsive-nav -->
		</div> <!-- end .responsive-menu -->

		{% block content %}

		{% endblock %}
	

		
		
		<!-- Footer -->
		<footer class="footer">
			<div class="top">
				<div class="container">
					<div class="row">
						<div class="col-sm-4">
							
						</div> <!-- end .col-sm-4 -->
						<div class="col-sm-4">
							
							<div class="social-icons">
								<a href="https://www.linkedin.com/in/bagheripayam/" class="social-icon" target="_blank"><i class="fa fa-linkedin"></i></a>
								<a href="https://github.com/payam1979" class="social-icon" target="_blank"><i class="fa fa-github"></i></a>
								<a href="https://join.skype.com/invite/syuU6iA12Phq" class="social-icon" target="_blank"><i class="fa fa-skype"></i></a>
								<a href="https://learn.microsoft.com/en-us/users/payambagheri-1444/" class="social-icon" target="_blank"><i class="fa fa-windows"></i></a>
								
								
							</div> <!-- end .social-icons -->
						</div> <!-- end .col-sm-4 -->
						<div class="col-sm-4">
							
						</div> <!-- end .col-sm-4 -->
					</div> <!-- end .row -->
				</div> <!-- end .container -->
			</div> <!-- end .footer -->
			<div class="bottom">Copyright &copy; P_B_P  All Rights Reserved.</div> <!-- end .bottom -->
		</footer> <!-- end .footer -->
		{% if messages %}
		{% for message in messages %}
		<script>alert('{{message}}');</script>
		{% endfor %}
		{% endif %}
		<!-- jQuery -->
		<script src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
		<!-- Bootstrap -->
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<!-- Inview -->
		<script src="{% static 'js/jquery.inview.min.js' %}"></script>
		<!-- SmoothScroll -->
		<script src="{% static 'js/smoothscroll.js' %}"></script>
		<!-- jQuery Knob -->
		<script src="{% static 'js/jquery.knob.min.js' %}"></script>
		<!-- Owl Carousel -->
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<!-- Isotope -->
		<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
		<!-- Images Loaded -->
		<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
		<!-- google maps -->
		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
		<!-- Scripts.js -->
		<script src="{% static 'js/scripts.js' %}"></script>

	</body>
</html>